server:
  port: 8080

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 1234

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 245172190974-ad2gqc9pl4n9hhfnckbltd1rsi2fnp3p.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
jwt:
  issuer: sangmin.lee@cyberone.kr
  secret_key: cyberone